/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/course/": {
    /** Get Courses */
    get: operations["get_courses_api_v1_course__get"];
    /** Create Course */
    post: operations["create_course_api_v1_course__post"];
  };
  "/api/v1/course/{course_id}": {
    /** Get Course */
    get: operations["get_course_api_v1_course__course_id__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Course */
    Course: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /** CreateCourse */
    CreateCourse: {
      /** Name */
      name: string;
      /** Description */
      description: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /** OneCourse */
    OneCourse: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Description */
      description: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Get Courses */
  get_courses_api_v1_course__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["Course"])[];
        };
      };
    };
  };
  /** Create Course */
  create_course_api_v1_course__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCourse"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OneCourse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Course */
  get_course_api_v1_course__course_id__get: {
    parameters: {
      path: {
        course_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OneCourse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
