"""Add pass_percent column to Course

Revision ID: 1ed700ca4d03
Revises: 902cc9be9055
Create Date: 2023-06-18 03:29:39.928848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed700ca4d03'
down_revision = '902cc9be9055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_course', sa.Column('pass_percent', sa.Integer(), server_default=sa.text('86'), nullable=False))
    op.create_check_constraint(
        'check_pass_percent_between_1_and_100',
        'app_course',
        'pass_percent >= 1 AND pass_percent <= 100',
    )
    op.create_unique_constraint('u_competencies_per_user', 'app_usercompetence', ['user_id', 'competence_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('u_competencies_per_user', 'app_usercompetence', type_='unique')
    op.drop_constraint(
        'check_pass_percent_between_1_and_100',
        'app_course',
        type_='check',
    )
    op.drop_column('app_course', 'pass_percent')
    # ### end Alembic commands ###
