"""create usercourse again

Revision ID: 34ef22eb976d
Revises: 8acc6ed30cb8
Create Date: 2023-05-02 16:04:48.126018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ef22eb976d'
down_revision = 'a4311da50971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_usercourse',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['app_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_usercourse_course_id'), 'app_usercourse', ['course_id'], unique=False)
    op.create_index(op.f('ix_app_usercourse_id'), 'app_usercourse', ['id'], unique=True)
    op.create_index(op.f('ix_app_usercourse_user_id'), 'app_usercourse', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_usercourse_user_id'), table_name='app_usercourse')
    op.drop_index(op.f('ix_app_usercourse_id'), table_name='app_usercourse')
    op.drop_index(op.f('ix_app_usercourse_course_id'), table_name='app_usercourse')
    op.drop_table('app_usercourse')
    # ### end Alembic commands ###
