"""Course/post association

Revision ID: 431b1df01c98
Revises: dd8cab8d69f5
Create Date: 2023-05-23 02:10:29.475959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431b1df01c98'
down_revision = 'dd8cab8d69f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_course_post_association',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['app_course.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['app_post.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'post_id')
    )
    op.create_index(op.f('ix_app_course_post_association_course_id'), 'app_course_post_association', ['course_id'], unique=False)
    op.create_index(op.f('ix_app_course_post_association_post_id'), 'app_course_post_association', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_course_post_association_post_id'), table_name='app_course_post_association')
    op.drop_index(op.f('ix_app_course_post_association_course_id'), table_name='app_course_post_association')
    op.drop_table('app_course_post_association')
    # ### end Alembic commands ###
