"""Add field attempt_amount for Topic

Revision ID: 5b791911c731
Revises: 22aeba17b059
Create Date: 2023-06-10 14:36:16.436480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b791911c731'
down_revision = '22aeba17b059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_topic', sa.Column('attempts_amount', sa.Integer(), server_default=sa.text('3'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_topic', 'attempts_amount')
    # ### end Alembic commands ###
