"""Add unique contraint to user courses

Revision ID: 641de8286960
Revises: 34ef22eb976d
Create Date: 2023-05-11 01:36:14.977738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641de8286960'
down_revision = '34ef22eb976d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_course', 'app_usercourse', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_course', 'app_usercourse', type_='unique')
    # ### end Alembic commands ###
