"""Add user_course_id column to TestAttempt

Revision ID: 6974cf1b7111
Revises: ff01cadfc522
Create Date: 2023-07-04 00:36:35.299950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6974cf1b7111'
down_revision = 'ff01cadfc522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_testattempt', sa.Column('user_course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_app_testattempt_user_course_id'), 'app_testattempt', ['user_course_id'], unique=False)
    op.create_foreign_key(None, 'app_testattempt', 'app_usercourse', ['user_course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_testattempt', type_='foreignkey')
    op.drop_index(op.f('ix_app_testattempt_user_course_id'), table_name='app_testattempt')
    op.drop_column('app_testattempt', 'user_course_id')
    # ### end Alembic commands ###
