"""Recreate UserAnswer

Revision ID: 902cc9be9055
Revises: d11c20691193
Create Date: 2023-06-17 02:19:46.460733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM


# revision identifiers, used by Alembic.
revision = '902cc9be9055'
down_revision = 'd11c20691193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_useranswer')

    op.create_table('app_useranswer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('_value', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('checked', 'unchecked', name='useranswerstatus'), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('task_type', PG_ENUM('single', 'multiple', 'text', name='tasktype', create_type=False), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['app_testattempt.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_useranswer_id'), 'app_useranswer', ['id'], unique=True)
    op.create_index(op.f('ix_app_useranswer_status'), 'app_useranswer', ['status'], unique=False)
    op.create_index(op.f('ix_app_useranswer_user_id'), 'app_useranswer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_useranswer')
    op.create_table('app_useranswer')
    # ### end Alembic commands ###
