"""create course topic

Revision ID: 81f148d485ea
Revises: 34ef22eb976d
Create Date: 2023-05-10 15:16:13.923494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f148d485ea'
down_revision = '34ef22eb976d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_topic',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['app_course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index', 'course_id', name='u_course_index')
    )
    op.create_index(op.f('ix_app_topic_course_id'), 'app_topic', ['course_id'], unique=False)
    op.create_index(op.f('ix_app_topic_id'), 'app_topic', ['id'], unique=True)
    op.create_index(op.f('ix_app_topic_index'), 'app_topic', ['index'], unique=False)
    op.create_index(op.f('ix_app_topic_name'), 'app_topic', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_topic_name'), table_name='app_topic')
    op.drop_index(op.f('ix_app_topic_index'), table_name='app_topic')
    op.drop_index(op.f('ix_app_topic_id'), table_name='app_topic')
    op.drop_index(op.f('ix_app_topic_course_id'), table_name='app_topic')
    op.drop_table('app_topic')
    # ### end Alembic commands ###
