"""create usercourse

Revision ID: 8acc6ed30cb8
Revises: a4311da50971
Create Date: 2023-05-02 15:57:24.538226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8acc6ed30cb8'
down_revision = 'a4311da50971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
