"""Create association table for posts and competencies

Revision ID: 9522f87b44ad
Revises: b21a2f752a65
Create Date: 2023-06-04 18:55:31.430745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9522f87b44ad'
down_revision = 'b21a2f752a65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_post_competence_association',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('competence_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['app_competence.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['app_post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'competence_id')
    )
    op.create_index(op.f('ix_app_post_competence_association_competence_id'), 'app_post_competence_association', ['competence_id'], unique=False)
    op.create_index(op.f('ix_app_post_competence_association_post_id'), 'app_post_competence_association', ['post_id'], unique=False)
    op.add_column('app_course_competence_association', sa.Column('competence_id', sa.BigInteger(), nullable=False))
    op.drop_index('ix_app_course_competence_association_post_id', table_name='app_course_competence_association')
    op.create_index(op.f('ix_app_course_competence_association_competence_id'), 'app_course_competence_association', ['competence_id'], unique=False)
    op.drop_constraint('app_course_competence_association_post_id_fkey', 'app_course_competence_association', type_='foreignkey')
    op.create_foreign_key(None, 'app_course_competence_association', 'app_competence', ['competence_id'], ['id'])
    op.drop_column('app_course_competence_association', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_course_competence_association', sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'app_course_competence_association', type_='foreignkey')
    op.create_foreign_key('app_course_competence_association_post_id_fkey', 'app_course_competence_association', 'app_competence', ['post_id'], ['id'])
    op.drop_index(op.f('ix_app_course_competence_association_competence_id'), table_name='app_course_competence_association')
    op.create_index('ix_app_course_competence_association_post_id', 'app_course_competence_association', ['post_id'], unique=False)
    op.drop_column('app_course_competence_association', 'competence_id')
    op.drop_index(op.f('ix_app_post_competence_association_post_id'), table_name='app_post_competence_association')
    op.drop_index(op.f('ix_app_post_competence_association_competence_id'), table_name='app_post_competence_association')
    op.drop_table('app_post_competence_association')
    # ### end Alembic commands ###
