"""Add check constraint to Topic and Task

Revision ID: 9b69cce1bdd4
Revises: 431b1df01c98
Create Date: 2023-05-28 14:15:52.348434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b69cce1bdd4'
down_revision = '431b1df01c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'check_prev_topic_id_is_not_self',
        'app_topic',
        'prev_topic_id <> id',
    )
    op.create_check_constraint(
        'check_prev_task_id_is_not_self',
        'app_task',
        'prev_task_id <> id',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'check_prev_topic_id_is_not_self',
        'app_topic',
        type_='check',
    )
    op.drop_constraint(
        'check_prev_task_id_is_not_self',
        'app_task',
        type_='check',
    )
    # ### end Alembic commands ###
