"""Create competencies

Revision ID: a28bb6191a7d
Revises: 6d7dfd548611
Create Date: 2023-06-05 00:04:32.604889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28bb6191a7d'
down_revision = '6d7dfd548611'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_competence',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_competence_id'), 'app_competence', ['id'], unique=True)
    op.create_index(op.f('ix_app_competence_name'), 'app_competence', ['name'], unique=True)
    op.create_table('app_course_competence_association',
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('competence_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['app_competence.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['app_course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'competence_id')
    )
    op.create_index(op.f('ix_app_course_competence_association_competence_id'), 'app_course_competence_association', ['competence_id'], unique=False)
    op.create_index(op.f('ix_app_course_competence_association_course_id'), 'app_course_competence_association', ['course_id'], unique=False)
    op.create_table('app_post_competence_association',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('competence_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['app_competence.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['app_post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'competence_id')
    )
    op.create_index(op.f('ix_app_post_competence_association_competence_id'), 'app_post_competence_association', ['competence_id'], unique=False)
    op.create_index(op.f('ix_app_post_competence_association_post_id'), 'app_post_competence_association', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_post_competence_association_post_id'), table_name='app_post_competence_association')
    op.drop_index(op.f('ix_app_post_competence_association_competence_id'), table_name='app_post_competence_association')
    op.drop_table('app_post_competence_association')
    op.drop_index(op.f('ix_app_course_competence_association_course_id'), table_name='app_course_competence_association')
    op.drop_index(op.f('ix_app_course_competence_association_competence_id'), table_name='app_course_competence_association')
    op.drop_table('app_course_competence_association')
    op.drop_index(op.f('ix_app_competence_name'), table_name='app_competence')
    op.drop_index(op.f('ix_app_competence_id'), table_name='app_competence')
    op.drop_table('app_competence')
    # ### end Alembic commands ###
