"""Create User model

Revision ID: a4311da50971
Revises: 941d2ba95e54
Create Date: 2023-04-29 13:29:14.307383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4311da50971'
down_revision = '941d2ba95e54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_course',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_course_id'), 'app_course', ['id'], unique=True)
    op.create_index(op.f('ix_app_course_name'), 'app_course', ['name'], unique=True)
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=128), server_default='', nullable=False),
    sa.Column('patronymic', sa.String(length=128), server_default='', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("email LIKE '%%___@___%%.__%%'", name='check_email_format'),
    sa.CheckConstraint('NOT (is_admin AND is_teacher)', name='check_one_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=True)
    op.create_index(op.f('ix_app_user_is_admin'), 'app_user', ['is_admin'], unique=False)
    op.create_index(op.f('ix_app_user_is_teacher'), 'app_user', ['is_teacher'], unique=False)
    op.drop_index('ix_course_description', table_name='course')
    op.drop_index('ix_course_id', table_name='course')
    op.drop_index('ix_course_name', table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='course_pkey')
    )
    op.create_index('ix_course_name', 'course', ['name'], unique=False)
    op.create_index('ix_course_id', 'course', ['id'], unique=False)
    op.create_index('ix_course_description', 'course', ['description'], unique=False)
    op.drop_index(op.f('ix_app_user_is_teacher'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_is_admin'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_app_course_name'), table_name='app_course')
    op.drop_index(op.f('ix_app_course_id'), table_name='app_course')
    op.drop_table('app_course')
    # ### end Alembic commands ###
