"""Create answer

Revision ID: ab35b63119c0
Revises: 9040106a2ac7
Create Date: 2023-05-15 00:24:56.723827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab35b63119c0'
down_revision = '9040106a2ac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_answer',
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['app_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'value', name='u_answer_value_for_task')
    )
    op.create_index(op.f('ix_app_answer_id'), 'app_answer', ['id'], unique=True)
    op.create_index(op.f('ix_app_answer_task_id'), 'app_answer', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_answer_task_id'), table_name='app_answer')
    op.drop_index(op.f('ix_app_answer_id'), table_name='app_answer')
    op.drop_table('app_answer')
    # ### end Alembic commands ###
