"""Create PostCompetence

Revision ID: efdd38aaab93
Revises: ba973b42da5f
Create Date: 2023-05-26 14:06:54.919397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdd38aaab93'
down_revision = 'ba973b42da5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_postcompetence',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['app_competence.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['app_post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'competence_id', name='u_post_competence')
    )
    op.create_index(op.f('ix_app_postcompetence_competence_id'), 'app_postcompetence', ['competence_id'], unique=False)
    op.create_index(op.f('ix_app_postcompetence_id'), 'app_postcompetence', ['id'], unique=True)
    op.create_index(op.f('ix_app_postcompetence_post_id'), 'app_postcompetence', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_postcompetence_post_id'), table_name='app_postcompetence')
    op.drop_index(op.f('ix_app_postcompetence_id'), table_name='app_postcompetence')
    op.drop_index(op.f('ix_app_postcompetence_competence_id'), table_name='app_postcompetence')
    op.drop_table('app_postcompetence')
    # ### end Alembic commands ###
