"""Create ChatMessage

Revision ID: ff01cadfc522
Revises: 1ed700ca4d03
Create Date: 2023-06-27 01:57:50.519800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff01cadfc522'
down_revision = '1ed700ca4d03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_chatmessage',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('sender_id <> recipient_id', name='check_sender_and_recipient_not_equal'),
    sa.ForeignKeyConstraint(['recipient_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sender_recipient_created_at', 'app_chatmessage', ['sender_id', 'recipient_id', sa.text('created_at DESC')], unique=True)
    op.create_index(op.f('ix_app_chatmessage_id'), 'app_chatmessage', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_chatmessage_id'), table_name='app_chatmessage')
    op.drop_index('idx_sender_recipient_created_at', table_name='app_chatmessage')
    op.drop_table('app_chatmessage')
    # ### end Alembic commands ###
