# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
    workflow_dispatch:

permissions:
    contents: read

jobs:
    backend:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -rrequirements.txt -rrequirements-test.txt

            - name: Run flake8
              run: |
                  python -m flake8 -v

            - name: Run tests
              run: |
                  pytest --cov

    frontend:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              working-directory: ./frontend
              run: |
                  yarn

            - name: Run eslint
              working-directory: ./frontend
              run: |
                  yarn lint
